service: serverless-102

provider:
  name: aws
  runtime: nodejs4.3

  # TODO: This will be needed for connecting with RDS through a VPC
  #
  # vpc:
  #   securityGroupIds:
  #     - securityGroupId1
  #     - securityGroupId2
  #   subnetIds:
  #     - subnetId1
  #     - subnetId2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  createUser:
    handler: handler.createUser
    description: Creates a user
    events:
      - http:
          path: users/create
          method: post

